name: Sync from Template

on:
  workflow_dispatch:
  schedule:
    - cron: '55 18 * * *'

jobs:
  template-sync:
    permissions:
      contents: write
      pull-requests: write
    uses: prinsfrank/CI-PHP/.github/workflows/template-sync.yml@main
